### ISSUE TITLE
Cannot compile simple "use netcdf" program

### ISSUE THREAD

**Issue by maddenp** [conda-forge/netcdf-fortran-feedstock#25]
I feel like this must be related to similar issues/questions raised recently in feedstock-eccodes, but I'm still a little lost. Given this `meta.yaml`
```
package:
  name: foo
  version: 0.0.1

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - netcdf-fortran

build:
  script: $FC $FFLAGS -c p.f90

source:
  path: .
```
and this `p.f90`
```
subroutine s
  use netcdf
end subroutine s
```
a subsequent `conda build -c conda-forge .` leads to
```
p.f90:2:6:

   use netcdf
      1
Fatal Error: Cannot read module file 'netcdf.mod' opened at (1), because it was created by a different version of GNU Fortran
```
Is this a matter of conda-forge using different compilers (via the `toolchain_*` packages) than what I get with no variant definitions when I use the `{{ compiler('fortran') }}` specification? I think maybe that's what I understood from the discussion in eccodes... And would the fix be to update the toolchain packages to use the same e.g. gfortran version that the Anaconda compilers use? I'm guessing that's a big lift that I probably wouldn't be able to help with, but please let me know if there's anything I can do.

In the meantime, I'm not sure there's anything better for me to do than to build a local package without the conda-forge variant definitions, which I'd hope would give me a compatible local package. Please let me know if I've misunderstood the situation.

Can/should something be done with pinning to catch this incompatibility before compilation is attempted?
